services:
  - type: web
    name: resume-analyzer
    env: python
    plan: free
    # The rootDir has been removed.
    buildCommand: "pip install -r resume-analyzer/requirements.txt"
    startCommand: "gunicorn resume-analyzer.app:app"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: SENDER_EMAIL
        sync: false
      - key: SENDER_PASSWORD
        sync: false
      - key: GOOGLE_API_KEY
        sync: false