services:
  - type: web
    name: resume-analyzer
    env: python
    plan: free
    
    # Build command stays the same, it needs the full path
    buildCommand: "pip install -r resume-analyzer/requirements.txt"
    
    # Start command now matches what Render wants by default
    startCommand: "gunicorn app:app"
    
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: SECRET_KEY
        generateValue: true