services:
  - type: web
    name: resume-analyzer
    env: python
    plan: free
    rootDir: resume-analyzer/deploy
    
    # Build command - install dependencies
    buildCommand: "pip install -r ../../requirements.txt"
    
    # Start command - use Flask directly since gunicorn path issues
    startCommand: "python app.py"
    
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: SECRET_KEY
        generateValue: true
      - key: FLASK_ENV
        value: production