services:
  - type: web
    name: resume-analyzer
    env: python
    plan: free # Free plan par database ke liye disk nahi milti
    buildCommand: "./render_build.sh"
    startCommand: "gunicorn resume-analyzer.app:app"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: DATABASE_URL # Isko Render Dashboard se manage karein
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: SENDER_EMAIL
        sync: false
      - key: SENDER_PASSWORD
        sync: false
      - key: SECRET_KEY
        generateValue: true # Render se generate karwayein