services:
  - type: web
    name: resume-analyzer
    env: python
    plan: free
    rootDir: resume-analyzer/deploy
    
    # Build command - install dependencies from root requirements.txt
    buildCommand: "pip install -r ../../requirements.txt"
    
    # Start command - run from deploy directory
    startCommand: "gunicorn app:app --bind 0.0.0.0:$PORT"
    
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: SECRET_KEY
        generateValue: true