services:
  - type: web
    name: resume-analyzer
    env: python
    plan: free
    
    # Per the docs, this is a common build command for Python
    buildCommand: "pip install -r resume-analyzer/requirements.txt"
    
    # This start command follows the format from the docs for your folder structure
    startCommand: "gunicorn resume-analyzer.app:app"
    
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.4
      - key: SECRET_KEY
        generateValue: true